apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::355130916517:role/eksctl-k8sClusterAkuUdacityUdagram-addon-iam-Role1-18VRAU8WRQQXY
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
