apiVersion: v1
kind: Service
metadata:
  name: akuudagram-backend-feed
  labels:
    app: akuudagram-backend-feed
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: appudagram-backend-feed
