apiVersion: v1
kind: Service
metadata:
  name: akuudagram-frontend
  labels:
    app: akuudagram-frontend
spec:
  type: LoadBalancer
  selector:
    app: akuudagram-frontend
  ports:
  - name: "frontend"
    port: 80
    targetPort: 80
