apiVersion: v1
kind: Service
metadata:
  name: akuudagram-backend-user
  labels:
    app: akuudagram-backend-user
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    app: akuudagram-backend-user
